spring:
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/fornecedor?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: update
